name: Deploy to climaofficial.com

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /domains/climaofficial.com/public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/database.rules.json
            **/firebase.json
            **/.firebase/**
            **/launch-plan.html
            **/affiliate-tracker.html
